source/config/routes.rb
TabsChallenge::Application.routes.draw do
  root :to => 'challenges#index'
  resources :challenges, :only => [:index]

  get "/unit/:id/challenges", to: "challenges#show"
  get "/challenge/:id/content", to: "challenges#content"
end

source/app/models/challenge.rb
class Challenge < ActiveRecord::Base
  belongs_to :unit

  IMAGES = %w{
    http://cdn.attackofthecute.com/December-13-2013-02-00-13-jj.jpg
    http://cdn.attackofthecute.com/April-15-2013-00-38-11-jljksdflkjdsf.jpg
    http://cdn.attackofthecute.com/February-08-2014-02-17-02-c.jpg
    http://cdn.attackofthecute.com/February-08-2014-04-00-47-sd.jpg
    http://cdn.attackofthecute.com/January-04-2013-19-39-37-hh.jpg
  }
  def self.grouped_by_phase_and_level
    # by_phase = Challenge.all.group_by {|challenge| "#{challenge.unit.phase.name}-#{challenge.unit.number}" }.sort_by{ |phase, level| level }
    # Hash[ by_phase ]
    by_phase = Unit.all.group_by {|unit| "#{unit.phase.name}-#{unit.number}"}.sort_by{ |phase, level| level }
    Hash[by_phase]
  end

  def image
    IMAGES.sample
  end
end

source/app/models/phase.rb
class Phase < ActiveRecord::Base
  has_many :units
end

source/app/models/unit.rb
class Unit < ActiveRecord::Base
  belongs_to :phase
  has_many :challenges

  def self.all_phase_units
    self.all.map { |unit| "#{unit.phase.name}-#{unit.number}" }
  end

  def self.all_phase_units_id
    self.all.map { |unit| unit.id }
  end
end

source/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

source/app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  def index
    @phase_units = Unit.all_phase_units
    @phase_unit_ids = Unit.all_phase_units_id
  end

  def show
    @unit_challenges = Unit.find(params[:id]).challenges.map{ |challenge| [challenge.name, challenge.id] }
    respond_to do |format|
      format.json { render json: @unit_challenges }
    end
  end

  def content
    @challenge = Challenge.find(params[:id])
    @challenge = [@challenge.image, @challenge.description, @challenge.id]
    respond_to do |format|
      format.json { render json: @challenge }
    end
  end

end

source/app/controllers/units_controller.rb
class UnitsController < ApplicationController
  def show
    @challenges = Unit.find(params[:id]).challenges
    render :show, :layout => false
  end
end

source/app/helpers/application_helper.rb
module ApplicationHelper
end

source/app/views/challenges/_challenge_content.html.erb
<li>
  <%= link_to challenge.name, '#' %>
  <div class="challenge-content">
    <%= image_tag challenge.image %>
    <%= challenge.description %>
  </div>
</li>

source/app/views/challenges/_challenges.html.erb
<div class="tab-content">
  <div class="tab-pane" id="1">
    <ul class="nav nav-tabs nav-stacked content">
      <li>Challenge Name
        <div class="challenge-content hidden">
          <!-- image -->
          <!-- description -->
        </div>
      </li>
    </ul>
  </div>
</div>

source/app/views/challenges/_phase_units.html.erb
<ul class="nav nav-tabs units">
  <% @phase_units.each_with_index do |phase_unit_string, idx| %>
    <li><%= link_to phase_unit_string, "/", data: {unit_id: @phase_unit_ids[idx]} %></li>
  <% end %>
</ul>
<!-- challenges should be pasted starting here -->
<div class="tab-content">
  <div class="tab-pane" id="1">
    <ul class="nav nav-tabs nav-stacked content">
      <!-- line items should be pasted here -->
    </ul>
  </div>
</div>

<li class="challenge-item hidden"><a href="#">Challenge Name 2</a>
  <div class="challenge-content hidden">
    <!-- image -->
    <!-- description -->
  </div>
</li>

source/app/views/challenges/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h3>Challenges</h3>
        <div class="tabbable tabs-left">
          <%= render 'phase_units', :phases => @phases %>
           <% #render 'challenges', :challenges => @challenges %>
        </div>
    </div>
  </div>
</div>

source/app/views/challenges/show.html.erb
<li>
  <h2><%= @challenge.name %></h2>
  <div class="challenge-content" id="<%= @challenge.id %>">
    <%= image_tag @challenge.image %>
    <%= @challenge.description %>
  </div>
</li>

source/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TabsChallenge</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

source/app/views/units/_challenge_content.html.erb
<li>
  <%= link_to challenge.name, '#' %>
  <div class="challenge-content" >
    <%= image_tag challenge.image %>
    <%= challenge.description %>
  </div>
</li>

source/app/views/units/show.html.erb
<div class="">

    <div class="tab-pane" id="<%= @challenges.first.unit.id %>">
      <ul class="nav nav-tabs nav-stacked content">
        <% @challenges.each do |challenge| %>
          <li><%= link_to challenge.name, unit_challenge_path(challenge.unit challenge), {:"data-toggle" => "##{challenge.name}",:remote => true, :class => "challenge_link"} %></li>
        <% end %>
      </ul>
    </div>

</div>